### ISSUE TITLE
About the training time of chem-paper

### ISSUE THREAD

**Issue by jkwang93** [cambridge-mlg/weighted-retraining#1]
Thanks for your code! It's a very greate work!
I want to run your Chem-paper code, but I found that it takes 2 hours for me to train an epoch on 1080ti. According to the default 500 epochs in your code, do I have to train for 50 days? It's taking too much time, isn't it?

**Comment by AustinT** [comment]
Hello, thanks for using our code!

Please try just letting it run and see what happens. The first iteration takes a long time since it is doing some model retraining; subsequent iterations should be shorter. I think the code should run within 10 hours based on what you have told me. Sorry that the progress bar is misleading.

Please let me know if it does finish in <10 hours and I will close this issue.

**Comment by jkwang93** [comment]
I have ran for about 12 hours, and found that the bar has been running repeatedly for epoch 0 of 5 times, and the time of running a epoch 0 is the same (2 hours) each time. After epoch 0 is completed, a new epoch 0 will be run, and it will fall into an infinite loop. The epoch will not go to 1.


  # Main loop
        with tqdm(
            total=args.query_budget, dynamic_ncols=True, smoothing=0.0, file=sys.stdout
        ) as pbar:
            for ret_idx in range(num_retrain):
                pbar.set_postfix(postfix)
                pbar.set_description("retraining")

                # Decide whether to retrain
                samples_so_far = args.retraining_frequency * ret_idx

                # Optionally do retraining
                num_epochs = args.n_retrain_epochs
                if ret_idx == 0 and args.n_init_retrain_epochs is not None:
                    num_epochs = args.n_init_retrain_epochs
                if num_epochs > 0:
                    retrain_dir = result_dir / "retraining"
                    version = f"retrain_{samples_so_far}"
                    retrain_model(
                        model, datamodule, retrain_dir, version, num_epochs, args.gpu
                    )
                del num_epochs

                # Update progress bar
                postfix["retrain_left"] -= 1
                pbar.set_postfix(postfix)
This part of the code is like this, I did not change.

**Comment by AustinT** [comment]
> I have ran for about 12 hours, and found that the bar has been running repeatedly for epoch 0 of 5 times, and the time of running a epoch 0 is the same (2 hours) each time. After epoch 0 is completed, a new epoch 0 will be run, and it will fall into an infinite loop. The epoch will not go to 1.
> # Main loop
> 
> ```
>     with tqdm(
>         total=args.query_budget, dynamic_ncols=True, smoothing=0.0, file=sys.stdout
>     ) as pbar:
>         for ret_idx in range(num_retrain):
>             pbar.set_postfix(postfix)
>             pbar.set_description("retraining")
> 
>             # Decide whether to retrain
>             samples_so_far = args.retraining_frequency * ret_idx
> 
>             # Optionally do retraining
>             num_epochs = args.n_retrain_epochs
>             if ret_idx == 0 and args.n_init_retrain_epochs is not None:
>                 num_epochs = args.n_init_retrain_epochs
>             if num_epochs > 0:
>                 retrain_dir = result_dir / "retraining"
>                 version = f"retrain_{samples_so_far}"
>                 retrain_model(
>                     model, datamodule, retrain_dir, version, num_epochs, args.gpu
>                 )
>             del num_epochs
> 
>             # Update progress bar
>             postfix["retrain_left"] -= 1
>             pbar.set_postfix(postfix)
> ```
> 
> This part of the code is like this, I did not change.

This is very strange. I certainly don't get an infinite loop when I run the code, and examining the logic of the script I don't see the possibility for an infinite loop to exist. I have several ideas of what you might be seeing:

1. Your terminal does not support rewriting of the progress bar, so you see a new progress bar every time the description changes, which makes it look like it is stuck at epoch 0.
2. You are mistaking multiple different runs as the same run and thinking that it is not progressing.
3. Your computer is VERY slow so it is just taking a long time.

You have not given me enough information to diagnose the problem, so if you want me to help you I will need you to give me more information. First, can you tell me?

- what operating system you are using?
- if you are using the exact conda environment that I have specified
- what shell you are using (run `echo $SHELL`)

Second, _please try running the following command_, which is a shortened version of the script. On my computer this takes around 10 minutes to run (note it will **not** show a progress bar when running). Please give it at least 2h to run in case your computer is very slow. It will produce a file called `github-issue.log`. Please show me the contents of this file and I can continue to help you diagnose this issue.

```
python weighted_retraining/opt_scripts/opt_chem.py --seed=1 --gpu --query_budget=20 --retraining_frequency=1000000 --result_root=logs/test/github-issue-1 --pretrained_model_file=assets/pretrained_models/chem.ckpt --lso_strategy=opt --train_path=data/chem/zinc/orig_model/tensors_train --val_path=data/chem/zinc/orig_model/tensors_val --vocab_file=data/chem/zinc/orig_model/vocab.txt --property_file=data/chem/zinc/orig_model/pen_logP_all.pkl --n_retrain_epochs=0.001 --n_init_retrain_epochs=0.01 --n_best_points=2000 --n_rand_points=8000 --n_inducing_points=500 --weight_type=rank --rank_weight_k=inf > github-issue.log
```

**Comment by jkwang93** [comment]
Thanks a lot ~~~

**Comment by jinzhezhang** [comment]
Hey just out of curiosity, have you succeeded to train the model within "reasonable" time? 
Me too seeing a 2h20 per epoch time and 500 epochs limit and wondering if I should keep the training running. 
I need to retrain the model from scratch (not only repeat the experiments) because I added more vocabularies.
@jkwang93  @AustinT

**Comment by AustinT** [comment]
> Hey just out of curiosity, have you succeeded to train the model within "reasonable" time?
> Me too seeing a 2h20 per epoch time and 500 epochs limit and wondering if I should keep the training running.
> I need to retrain the model from scratch (not only repeat the experiments) because I added more vocabularies.
> @jkwang93 @AustinT

Hi, this is normal behaviour. However, *the first epoch will take much longer than the next epochs*, so if you leave it running it should hopefully complete within 24h, even though it might seem like it will take 1000h now.
