### ISSUE TITLE
Chem data in official results

### ISSUE THREAD

**Issue by jinzhezhang** [cambridge-mlg/weighted-retraining#4]
Hi, 

I checked some Chem data in the "official results" repository. It seems that some of the random seeds have only 5 or 8 epochs instead of 10 (in another word, the query number from gp_opt is less than 500). Is there a particular reason you have not included data from those later epochs?

**Comment by AustinT** [comment]
> Hi,
> 
> I checked some Chem data in the "official results" repository. It seems that some of the random seeds have only 5 or 8 epochs instead of 10 (in another word, the query number from gp_opt is less than 500). Is there a particular reason you have not included data from those later epochs?

Good question! It is because the script crashed when we ran it. The JTNN sometimes crashes for no obvious reason and this happened when we ran our experiments.

**Comment by jinzhezhang** [comment]
I see, this is exactly what I am asking. It should be a Cholesky decomposition issue related to the fact that current implementation is set as float32 which lacks of precision. We spend quite a bit time to get this solved. Do you want us to create a PR for this?

**Comment by AustinT** [comment]
> I see, this is exactly what I am asking. It should be a Cholesky decomposition issue related to the fact that current implementation is set as float32 which lacks of precision. We spend quite a bit time to get this solved. Do you want us to create a PR for this?

If it's not too much work then a PR would be great! If it is a lot of work then don't bother, because this code base is not very good anyway :stuck_out_tongue:
