### ISSUE TITLE
Potential Mistake in Variable Name

### ISSUE THREAD

**Issue by onurboyar** [cambridge-mlg/weighted-retraining#5]
Hello,

Thank you for open-sourcing your work.

In the line 102-103 of the following file:
https://github.com/cambridge-mlg/weighted-retraining/blob/master/weighted_retraining/shapes/shapes_data.py

you write:

```
            self.train_data = np.concatenate(
                [self.data_train[len(x_new) :], x_new], axis=0
            )

```

I guess there is a mistake here since you already have self.data_train and use it in the following **else** clause. In my understanding, the code should be:

```
            self.data_train = np.concatenate(
                [self.data_train[len(x_new) :], x_new], axis=0
            )

```

**Comment by AustinT** [comment]
Hi, thank you for raising this issue. This does look like a bug: thanks for spotting it. I will confirm and follow up on this later (maybe in 2 weeks).

If it is a bug, it may make the results for the FB-VAE baseline in our paper better than we initially reported.

**Comment by onurboyar** [comment]
Glad to help, thanks for your work, it helps me a lot.

**Comment by AustinT** [comment]
I agree that this was a bug and have pushed a fix. I think its not worth updating the paper for, but I did add an announcement to the README file where I mentioned this bug. Thanks @onurboyar for pointing this out!
